### ISSUE TITLE
Doc Issue with Async Client Example Code

### ISSUE THREAD

**Issue by kiwisincebirth** [mailgun/mailgun-java#12]
## Issue

In the main readme for the project you list the following example.

``` 
        MailgunMessagesApi mailgunAsyncMessagesApi = MailgunClient.config(PRIVATE_API_KEY)
            .createAsyncApi(MailgunMessagesApi.class);

        Message message = Message.builder()
                .from(EMAIL_FROM)
                .to(EmailUtil.emailWithName(USER_NAME, USER_EMAIL)
                .subject(SUBJECT)
                .text(TEXT)
                .build();

        CompletableFuture<MessageResponse> result = mailgunAsyncMessagesApi.sendMessageAsync(MAIN_DOMAIN, message);
```

Running this code produces an error

```
Caused by: java.lang.NullPointerException: Cannot invoke "feign.AsyncClient.execute(feign.Request, feign.Request$Options, java.util.Optional)" because "client" is null
	at feign.AsyncFeign$AsyncBuilder.lambda$stageExecution$1(AsyncFeign.java:220)
	at feign.SynchronousMethodHandler.executeAndDecode(SynchronousMethodHandler.java:121)
	at feign.SynchronousMethodHandler.invoke(SynchronousMethodHandler.java:91)
	at feign.ReflectiveFeign$FeignInvocationHandler.invoke(ReflectiveFeign.java:100)
	at jdk.proxy2/jdk.proxy2.$Proxy157.sendMessageAsync(Unknown Source)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at feign.ReflectiveAsyncFeign$AsyncFeignInvocationHandler.invoke(ReflectiveAsyncFeign.java:66)
	at jdk.proxy2/jdk.proxy2.$Proxy157.sendMessageAsync(Unknown Source)
```

The underlying issue is the class `MailgunClientBuilder` has a uninitialised property `client`. The documentation omitts its configuration.

## Solution

After some basic investigation, something like this is needed.

``` 
        AsyncClient client = new AsyncClient.Default(
                new Client.Default(null, null),
                Executors.newSingleThreadExecutor()
        );

        MailgunMessagesApi mailgunAsyncMessagesApi = MailgunClient.config(PRIVATE_API_KEY)
                .client(client) // This is the missing property
                .createAsyncApi(MailgunMessagesApi.class);

       // The rest of the sample code is ok.
```

You should look to improve the documentation

**Comment by szagr** [comment]
@kiwisincebirth, thanks for raising this issue!
The root cause of it - OpenFeign removed the null check on the AsyncClient in the last version
https://github.com/OpenFeign/feign/blob/feign-11/core/src/main/java/feign/AsyncFeign.java#L142
Now we should handle it by ourselves.
The default AsyncClient will be added in the next release.

**Comment by szagr** [comment]
Default AsyncClient was added in v1.0.4

**Comment by kiwisincebirth** [comment]
@szagr - my example `Executors.newSingleThreadExecutor()` - was just a (bad) example - ideally this should be something the consumer of the API provides
