### ISSUE TITLE
Serialisation Issue with Zoned DateTime

### ISSUE THREAD

**Issue by kiwisincebirth** [mailgun/mailgun-java#13]
Running the Code (Kotlin) 

```
fun main() {
    val PRIVATE_API_KEY = "zzzzzzzzzzzz"
    val DOMAIN = "sandbox.mailgun.org"
    val TEMPLATE_NAME = "test_template"

    val mailgunTemplatesApi = MailgunClient.config(PRIVATE_API_KEY)
        .createApi<MailgunTemplatesApi>(MailgunTemplatesApi::class.java)

    val response = mailgunTemplatesApi.getAllTemplateVersions(DOMAIN, TEMPLATE_NAME)
}
```

i am getting a serialisation issue. 

```
Exception in thread "main" feign.FeignException: Cannot deserialize value of type `java.time.ZonedDateTime` from String "Tue, 27 Sep 2022 01:17:34 UTC": Failed to deserialize java.time.ZonedDateTime: (java.time.format.DateTimeParseException) Text 'Tue, 27 Sep 2022 01:17:34 UTC' could not be parsed at index 8
 at [Source: (BufferedReader); line: 1, column: 677] (through reference chain: com.mailgun.model.templates.TemplateAllVersionsResponse$TemplateAllVersionsResponseBuilder["template"]->com.mailgun.model.templates.TemplateWithVersions$TemplateWithVersionsBuilder["createdAt"]) reading GET https://api.mailgun.net/v3/sandbox9f3dc5491e3642ec9c9d35a4e4c9a0f2.mailgun.org/templates/test_template/versions
	at feign.FeignException.errorReading(FeignException.java:167)
	at feign.InvocationContext.proceed(InvocationContext.java:42)
	at feign.AsyncResponseHandler.decode(AsyncResponseHandler.java:116)
	at feign.AsyncResponseHandler.handleResponse(AsyncResponseHandler.java:89)
	at feign.SynchronousMethodHandler.executeAndDecode(SynchronousMethodHandler.java:141)
	at feign.SynchronousMethodHandler.invoke(SynchronousMethodHandler.java:91)
	at feign.ReflectiveFeign$FeignInvocationHandler.invoke(ReflectiveFeign.java:100)
	at jdk.proxy2/jdk.proxy2.$Proxy5.getAllTemplateVersions(Unknown Source)
	at TestIssueWithMailgunLibraryKt.main(TestIssueWithMailgunLibrary.kt:19)
	at TestIssueWithMailgunLibraryKt.main(TestIssueWithMailgunLibrary.kt)
Caused by: com.fasterxml.jackson.databind.exc.InvalidFormatException: Cannot deserialize value of type `java.time.ZonedDateTime` from String "Tue, 27 Sep 2022 01:17:34 UTC": Failed to deserialize java.time.ZonedDateTime: (java.time.format.DateTimeParseException) Text 'Tue, 27 Sep 2022 01:17:34 UTC' could not be parsed at index 8
 at [Source: (BufferedReader); line: 1, column: 677] (through reference chain: com.mailgun.model.templates.TemplateAllVersionsResponse$TemplateAllVersionsResponseBuilder["template"]->com.mailgun.model.templates.TemplateWithVersions$TemplateWithVersionsBuilder["createdAt"])
	at com.fasterxml.jackson.databind.exc.InvalidFormatException.from(InvalidFormatException.java:67)
	at com.fasterxml.jackson.databind.DeserializationContext.weirdStringException(DeserializationContext.java:1991)
	at com.fasterxml.jackson.databind.DeserializationContext.handleWeirdStringValue(DeserializationContext.java:1219)
	at com.fasterxml.jackson.datatype.jsr310.deser.JSR310DeserializerBase._handleDateTimeException(JSR310DeserializerBase.java:176)
	at com.fasterxml.jackson.datatype.jsr310.deser.InstantDeserializer._fromString(InstantDeserializer.java:307)
	at com.fasterxml.jackson.datatype.jsr310.deser.InstantDeserializer.deserialize(InstantDeserializer.java:217)
	at com.fasterxml.jackson.datatype.jsr310.deser.InstantDeserializer.deserialize(InstantDeserializer.java:51)
	at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeSetAndReturn(MethodProperty.java:158)
	at com.fasterxml.jackson.databind.deser.BuilderBasedDeserializer.vanillaDeserialize(BuilderBasedDeserializer.java:293)
	at com.fasterxml.jackson.databind.deser.BuilderBasedDeserializer.deserialize(BuilderBasedDeserializer.java:217)
	at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeSetAndReturn(MethodProperty.java:158)
	at com.fasterxml.jackson.databind.deser.BuilderBasedDeserializer.vanillaDeserialize(BuilderBasedDeserializer.java:293)
	at com.fasterxml.jackson.databind.deser.BuilderBasedDeserializer.deserialize(BuilderBasedDeserializer.java:217)
	at com.fasterxml.jackson.databind.deser.DefaultDeserializationContext.readRootValue(DefaultDeserializationContext.java:323)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4674)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3658)
	at feign.jackson.JacksonDecoder.decode(JacksonDecoder.java:65)
	at feign.InvocationContext.proceed(InvocationContext.java:36)
	... 8 more
Caused by: java.time.format.DateTimeParseException: Text 'Tue, 27 Sep 2022 01:17:34 UTC' could not be parsed at index 8
	at java.base/java.time.format.DateTimeFormatter.parseResolved0(DateTimeFormatter.java:2052)
	at java.base/java.time.format.DateTimeFormatter.parse(DateTimeFormatter.java:1880)
	at com.fasterxml.jackson.datatype.jsr310.deser.InstantDeserializer._fromString(InstantDeserializer.java:301)
	... 21 more
```

I am running inside a Spring Boot (2.7.3) project, which bring fairly new versions of most libraries. 

I am really not sure where to go at this point. I have tested using the Feign responses, and used the `ObjectMapperUtil.decode()` function, but get a similar error message. ObjectMapperUtil uses it own configured Jackson Object mapper, so I don't believe it can be anything I am doing in my project. 

Is it possible to test a basic example independently, I would at least like to know if the issue is specific to me.

**Comment by szagr** [comment]
Hi Mark.
It's weird.
Do you use the last version of Mailgun Java SDK - 1.0.3?
If I use Postman
{{BASE_URL}}/{{mydomain}}/templates/{{templateName}}/versions
I got the same format as yours - `Sat, 05 Mar 2022 13:21:48 UTC`
And from java, it is successfully converted to ZonedDateTime:
<img width="496" alt="Screenshot 2022-10-09 at 13 46 36" src="https://user-images.githubusercontent.com/44971375/194752504-323cc33d-3e1d-4388-974c-9492a00e0f99.png">

**Comment by kiwisincebirth** [comment]
Yes am on `1.0.3` of the library. 

Leave i with me for the moment. When I get a chance, ill put together and share a sample app to test it with something close to my environment. To workaround the issue I am returning into Feign Response, then deserialising into my own set of object that have the `createdAt` field as a `String`

**Comment by szagr** [comment]
@kiwisincebirth 
Could you please tell me what is your locale?

**Comment by szagr** [comment]
Could you please try version 1.0.7?

**Comment by kiwisincebirth** [comment]
@szagr 
> Could you please tell me what is your locale?
Sydney/Australia

**Comment by kiwisincebirth** [comment]
It might be configuration of the Jackson deserialiser, noting the use of `InstantDeserializer` in the stack trace.

**Comment by szagr** [comment]
Did you try version 1.0.7?

**Comment by kiwisincebirth** [comment]
I have fully retested, and the issue (reported in original code) is resolved. Happy for you to close this issue. 

Both 1.0.3 and 1.0.7 are working without error, suspect the issue is in my code, and related to the Jackson deserialiser being used.
