### ISSUE TITLE
Android Support

### ISSUE THREAD

**Issue by timokz** [mailgun/mailgun-java#20]
Unfortunately, the suggested examples don't work for android, since the used HTTP Client wants to access an Instance field not found on the Android OS. Will using a different or custom client resolve this issue? 

```
java.lang.NoSuchFieldError: No static field INSTANCE of type Lorg/apache/http/conn/ssl/AllowAllHostnameVerifier; in class Lorg/apache/http/conn/ssl/AllowAllHostnameVerifier; or its superclasses (declaration of 'org.apache.http.conn.ssl.AllowAllHostnameVerifier' appears in /system/framework/framework.jar!classes4.dex)
                                                                                                    	at org.apache.http.conn.ssl.SSLConnectionSocketFactory.<clinit>(SSLConnectionSocketFactory.java:144)
                                                                                                    	at org.apache.http.conn.ssl.SSLConnectionSocketFactory.getSocketFactory(SSLConnectionSocketFactory.java:172)
                                                                                                    	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.getDefaultRegistry(PoolingHttpClientConnectionManager.java:109)
                                                                                                    	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.<init>(PoolingHttpClientConnectionManager.java:116)
                                                                                                    	at com.mashape.unirest.http.options.Options.refresh(Options.java:72)
                                                                                                    	at com.mashape.unirest.http.options.Options.<clinit>(Options.java:46)
                                                                                                    	at com.mashape.unirest.http.options.Options.getOption(Options.java:42)
                                                                                                    	at com.mashape.unirest.http.HttpClientHelper.prepareRequest(HttpClientHelper.java:151)
                                                                                                    	at com.mashape.unirest.http.HttpClientHelper.request(HttpClientHelper.java:131)
                                                                                                    	at com.mashape.unirest.request.BaseRequest.asJson(BaseRequest.java:68)
```

**Comment by szagr** [comment]
The suggested examples are specified for this particular java library.
As I see from your log, you use unirest?
And it's unclear from your example what endpoint/method you're using.

**Comment by timokz** [comment]
Hey, thanks for your reply! I replaced unirest with volley, which resolved the issue.
