### ISSUE TITLE
Java 16 Compatibility issue

### ISSUE THREAD

**Issue by namitkarlekar** [mailgun/mailgun-java#5]
I'm using this with JDK 17 and I get the following issue: 

Caused by: java.lang.reflect.InaccessibleObjectException: Unable to make Caused by: java.lang.reflect.InaccessibleObjectException: Unable to make java.lang.invoke.MethodHandles$Lookup(java.lang.Class) accessible: module java.base does not "opens java.lang.invoke" to unnamed module @614ddd49
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:354)
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297)
	at java.base/java.lang.reflect.Constructor.checkCanSetAccessible(Constructor.java:188)
	at java.base/java.lang.reflect.Constructor.setAccessible(Constructor.java:181)
	at com.mailgun.util.MailgunApiUtil.lambda$getFullUrl$0(MailgunApiUtil.java:22)
	at jdk.proxy2/jdk.proxy2.$Proxy147.getApiVersion(Unknown Source)
	at com.mailgun.util.MailgunApiUtil.getFullUrl(MailgunApiUtil.java:32)
	at com.mailgun.client.MailgunClient$MailgunClientBuilder.createApi(MailgunClient.java:180)

It doesn't like this: 
![image](https://user-images.githubusercontent.com/75053206/177534244-04389727-4214-4e8e-8ca1-33be9ff5dde5.png)

**Comment by namitkarlekar** [comment]
Sure there's a workaround, but it's not the best option: 
--add-opens java.base/java.lang.invoke=ALL-UNNAMED

**Comment by szagr** [comment]
@namitkarlekar thanks for raising this issue!
Fixed in v1.0.2
Sorry for the late reply.
